---
title: "Analysis"
output: html_notebook
---

# Set-up

```{r set-up, message=FALSE, warning=FALSE, paged.print=FALSE}

library(tidyverse)
library(rstan)
options(mc.cores = parallel::detectCores())

```

# Preparing data

```{r download-data, message=FALSE, warning=FALSE}

fouls <- bind_rows(
  
  e0_1617 = read_csv("http://www.football-data.co.uk/mmz4281/1617/E0.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1617"),
  
  e0_1718 = read_csv("http://www.football-data.co.uk/mmz4281/1718/E0.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1718"),
  
  e0_1819 = read_csv("http://www.football-data.co.uk/mmz4281/1819/E0.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1819"),
  
  f1_1617 = read_csv("http://www.football-data.co.uk/mmz4281/1617/F1.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1617"),

  f1_1718 = read_csv("http://www.football-data.co.uk/mmz4281/1718/F1.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1718"),

  f1_1819 = read_csv("http://www.football-data.co.uk/mmz4281/1819/F1.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1819"),
  
  d1_1617 = read_csv("http://www.football-data.co.uk/mmz4281/1617/D1.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1617"),

  d1_1718 = read_csv("http://www.football-data.co.uk/mmz4281/1718/D1.csv") %>%
    mutate(VAR = 1, Date = lubridate::dmy(Date), season = "s1718"),

  d1_1819 = read_csv("http://www.football-data.co.uk/mmz4281/1819/D1.csv") %>%
    mutate(VAR = 1, Date = lubridate::dmy(Date), season = "s1819"),

  i1_1617 = read_csv("http://www.football-data.co.uk/mmz4281/1617/I1.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1617"),

  i1_1718 = read_csv("http://www.football-data.co.uk/mmz4281/1718/I1.csv") %>%
    mutate(VAR = 1, Date = lubridate::dmy(Date), season = "s1718"),

  i1_1819 = read_csv("http://www.football-data.co.uk/mmz4281/1819/I1.csv") %>%
    mutate(VAR = 1, Date = lubridate::dmy(Date), season = "s1819"),

  sp1_1617 = read_csv("http://www.football-data.co.uk/mmz4281/1617/SP1.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1617"),

  sp1_1718 = read_csv("http://www.football-data.co.uk/mmz4281/1718/SP1.csv") %>%
    mutate(VAR = 0, Date = lubridate::dmy(Date), season = "s1718"),

  sp1_1819 = read_csv("http://www.football-data.co.uk/mmz4281/1819/SP1.csv") %>%
    mutate(VAR = 1, Date = lubridate::dmy(Date), season = "s1819")
) %>%
  select(Div:AwayTeam, HF, AF, VAR, season) %>%
  filter(!is.na(HF), !is.na(AF)) %>%
  rename("home_fouls" = "HF",
         "home_team" = "HomeTeam",
         "away_fouls" = "AF",
         "away_team" = "AwayTeam",
         "div" = "Div",
         "date" = "Date")

```

```{r split-data}

home <- fouls %>% 
  select(div, season, date, team = home_team, fouls = home_fouls, VAR)
away <- fouls %>%
  select(div, season, date, team = away_team, fouls = away_fouls, VAR)

```

```{r data-as-list}

X <- model.matrix(~ VAR + season*div, fouls)

X <- X[, sqrt(abs(diag(qr.R(qr(X))))) > 1]

fac_home <- factor(home$team)
fac_away <- factor(away$team)
fac <- fct_unify(list(fac_home, fac_away))

stan.data <- list(N = nrow(X),
                  away_fouls = away$fouls,
                  home_fouls = home$fouls,
                  X = X,
                  k = ncol(X),
                  home_team = as.numeric(fac[[1]]),
                  away_team = as.numeric(fac[[2]]),
                  N_teams = length(levels(fac[[1]]))
                  )

```

# Descriptive statistics

# Statistical model

```{r run-stan, message=FALSE, warning=FALSE, paged.print=FALSE}

sims <- 2000 # used also later for simulations
iterations <- (sims / parallel::detectCores()) * 2

posterior <-
  rstan::stan(
    file = "model/bivariate_lognormal_poisson.stan",
    data = stan.data,
    iter = iterations,
    control = list(max_treedepth = 12,
                   adapt_delta = 0.85)
  )

```

```{r save-posterior}

write_rds(posterior, "posterior/bivariate_lognormal_poisson.rds")

```

## Results

```{r print-betas}

broom::tidyMCMC(posterior, pars = c("home_beta", "away_beta"), 
                conf.int =  TRUE, conf.level = 0.9) %>% 
  mutate(side = if_else(str_detect(term, "home"), "home", "away"),
         term = rep(colnames(X), times = 2))

```

```{r print-hyperparameters}

print(posterior, pars = c("home_sd", "away_sd", "rho", "home_team_sd", "away_team_sd"))

```

## Simulations

```{r extract-betas}

home_beta <- as.matrix(posterior, pars = "home_beta")
away_beta <- as.matrix(posterior, pars = "away_beta")

```

```{r extract-re}

home_sd <- as.matrix(posterior, pars = "home_sd")
away_sd <- as.matrix(posterior, pars = "away_sd")

home_re <- as.matrix(posterior, pars = "home")
colnames(home_re) <- levels(fac_home)

away_re <- as.matrix(posterior, pars = "away")
colnames(away_re) <- levels(fac_away)

```

```{r extract-sigma}

L_Sigma <- posterior %>% 
  as.matrix(pars = "Sigma") %>% 
  array(dim = c(sims, 2, 2)) %>% 
  apply(MARGIN = 1, FUN = function(X) {
      t(chol(X))
    })

dim(L_Sigma) <- c(2, 2, sims)

Z <- L_Sigma %>% 
  apply(MARGIN = 3, FUN = function(X) {
      X %*% matrix(rnorm(2), nrow = 2)
    }) %>% 
  t()

```

```{r scenario}

# Reference: Germany (DivD1), season: 16/17
X_tilde <- tribble(
  ~`(Intercept)`, ~VAR, ~seasons1718, ~seasons1819, ~DivE0, ~DivF1, ~DivI1, ~DivSP1,
               1,    0,           0,             0,      0,      0,      0,       0,
               1,    1,           0,             0,      0,      0,      0,       0
) %>% as.matrix()

X_tilde

```

```{r compute-expectations}

Q_home <- exp(X_tilde %*% t(home_beta) + rnorm(sims, 0, home_sd) + t(Z)[1,])
Q_away <- exp(X_tilde %*% t(away_beta) + rnorm(sims, 0, away_sd) + t(Z)[2,])

Q <- Q_home + Q_away

matrixStats::rowQuantiles(Q, probs = c(0.05, 0.25, 0.5, 0.75, 0.95))

```

```{r simulate-yrep}



```
































